### PR TITLE
feat(class,program,accounts): add responsive design

### PR DESCRIPTION
**Pull request by MatoPlus**
### Notion ticket link

[Start Mobile Responsive Designs for static pages](https://www.notion.so/uwblueprintexecs/Start-Mobile-Responsive-Designs-for-static-pages-71b40c3d94f1448ab3fde0ca1d376fb8)

### Implementation description

https://user-images.githubusercontent.com/44826218/139608721-2a542ae3-b463-4183-a605-8f4b69530467.mp4

https://user-images.githubusercontent.com/44826218/139608726-98ab2848-d1c3-4a1a-90f7-00308e9082fd.mp4

https://user-images.githubusercontent.com/44826218/139608844-872882bc-0681-424a-90b3-12fa2aee0e1e.mp4

- Add mobile responsive designs to program details
  - Use breakpoints to do responsive designs
  - Use breakpoint value hook to do responsive displacements (tag position)
- Add mobile res design for my classes
  - Use breakpoints to do responsive designs
  - Use breakpoint value hook to do responsive displacements (join button position)
- Add mobile res design for my accounts
  - Use breakpoints to do responsive designs
  - Use breakpoint value hook to do responsive displacements (join button position)

### What should reviewers focus on?

- Dev: How mobile responsive designs are done - workflow/style
- Design: look and feel
- Design: I made a compromise to the my accounts page responsive designs for my own sanity :P. Lmk if it looks okay.

### Checklist

-   [X] My PR name is descriptive and in imperative tense
-   [X] I have run the linter
-   [X] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Comment by MatoPlus** [comment]
@vedantdsn @bekahma Some of these changes are pretty rush, but the goal atm is to get a reasonable responsive design in without worrying to much is internal is a much higher priority.
@neelismail01 is working on some other pages as well. Look forward to his changes in his upcoming PR!

**Comment by MatoPlus** [comment]
Added better padding, not shown in video
better-paddingY-classes
better-paddingY-program-details
:

**Review by bekahma — APPROVED** [review]
understand that some compromise has to be done given the deadlines so it looks totally fine if the margins aren't perfect for some cards! thanks for tackling the responsive design portion :)

**Comment by neelismail01** [comment]
Your changes look great to me! The webpages looked natural at mobile device widths and the use of the breakpoint hook to achieve that is clean. Nice job!

**Review by neelismail01 — APPROVED** [review]
Looks good to me

**Pull request merged**
