### PR TITLE
feat(admin browse internal users): table page and button to revoke/delete user

### PR DESCRIPTION
**Pull request by MatoPlus**
### Notion ticket link

[Brose Admin/Teacher Page](https://www.notion.so/uwblueprintexecs/Browse-Teacher-Admin-Page-b061219b53cb4d149ed91e60f9d4627e)
[Add - or n/a on empty fields in table](https://www.notion.so/uwblueprintexecs/Add-or-N-A-on-empty-fields-in-new-tables-on-internal-platform-b42d05abf1c84d2fbe877c13d0b0bba6)

### Implementation description

https://user-images.githubusercontent.com/44826218/141700563-4d6e9abd-cfce-483b-b5f6-4fea0e3b51f3.mp4

- Add new page under `/admin/user`
- The flow is very similar to `/admin/registrant` where we are using `react-table` with Chakra UI integrations, using global filters to search on all columns
- Reuse export feature via `react-csv`
- Make program admin cascade delete when corresponding user is deleted
- Update `schema.prisma` with referential actions
- Fix a lot of missing typing with sessions and tables
- Add util for authorization checks for api

### Steps to test

1. go the the `/admin/user` page as an admin user (this page should not be accessible by teachers)
2. test the admin tab, all the current admins should be shown on the table
3. revoking an admin user should be successful, you should not be able to revoke yourself

### What should reviewers focus on?

-

### Checklist

-   [ ] My PR name is descriptive and in imperative tense
-   [ ] I have run the linter
-   [ ] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Comment by MatoPlus** [comment]
Updated revoke flow with modals

https://user-images.githubusercontent.com/44826218/141712641-2fb948a9-77d8-4fde-a28a-f91778897de6.mp4

:

**Comment by MatoPlus** [comment]
Also fixed the table null cases:
image
image
image

Students tables
- `empty Grade -> -`
- `empty city -> N/A`

Volunteer tables
- `empty city -> N/A`

**Review by bekahma — APPROVED** [review]
wah this is a meaty ticket LOL but thanks for thinking of all the edge cases.

one question: is there a reason you went with a different confirmation modal design? and if it's because of chakra components, can we change the other modal designs for consistency? i don't have a strong preference so just wanted to clarify. i do think the red is a good choice for an "almost irreversible" action like deleting admin/teacher as opposed to the dark blue sdc colour.

**Comment by MatoPlus** [comment]
> one question: is there a reason you went with a different confirmation modal design? and if it's because of chakra components, can we change the other modal designs for consistency? i don't have a strong preference so just wanted to clarify. i do think the red is a good choice for an "almost irreversible" action like deleting admin/teacher as opposed to the dark blue sdc colour.

@bekahma  That's a good question very good question. Did you follow this thread? If so, what are your thoughts? https://uwblueprint.slack.com/archives/C02GA0V3NJ2/p1636984401001400?thread_ts=1636981986.001200&cid=C02GA0V3NJ2

but basically
```
I currently have something like the following, 1. delete button is red to point out that it is a destructive action. 2. Title also specify which user is being deleted
```

I can make it more "like" the other modal designs. I choose to follow the og modal just to make my life a bit easier: https://chakra-ui.com/docs/overlay/alert-dialog

If you guys want me to tweak the designs a bit, I can totally do that! just hmu

cc: @vedantdsn

**Comment by MatoPlus** [comment]
I'm going to merge this ticket for now! @bekahma lmk if you wanna follow up on this and I'll make another ticket!

**Pull request merged**
